# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

#def flutterModulePod
#  pod 'Flutter', :path => '../flutter_module/build/ios/framework/Debug/Flutter.podspec'
#end
#
#def flutterRegistrantPod
#  pod 'FlutterPluginRegistrant', :path => '../flutter_module/.ios/Flutter/FlutterPluginRegistrant/FlutterPluginRegistrant.podspec' , :inhibit_warnings => true
#end


target 'host_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  flutter_application_path = '../flutter_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)

  # Pods for host_app
#  flutterModulePod
#  flutterRegistrantPod
  post_install do |installer|
    flutter_post_install(installer) if defined?(flutter_post_install)
  end

end
